# Generated by Django 4.0.3 on 2022-04-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0002_rename_image_book_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_path',
            field=models.FilePathField(path='/static/covers'),
        ),
    ]
