# Generated by Django 4.0.3 on 2022-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0007_alter_book_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('school', 'school'), ('university', 'university'), ('after', 'after')], default='after', max_length=10),
        ),
    ]
