# Generated by Django 4.0.3 on 2022-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0008_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_path',
            field=models.FilePathField(path='\\static\\covers'),
        ),
    ]
