# Generated by Django 4.0.3 on 2022-04-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0012_alter_book_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_path',
            new_name='image',
        ),
    ]
